// test_ingest.mjs — T4, ingest verification.
//
// Plain node, assert-based, no test framework (CLAUDE.md hard rule 6).
// Exits non-zero on any mismatch.
//
// What this proves, and why each part is here:
//
//   1. CELL-BY-CELL PARITY against an independent ~30-line JS reference
//      parser (split on newline, split on comma, parseFloat). The WASM
//      parser is trusted because of this comparison, not because the charts
//      look right — every footgun in this project produces plausible numbers
//      rather than an error.
//   2. BLOCK INDEPENDENCE: the same file parsed with its blocks fed in
//      reverse order must produce a byte-identical cube. That is the only
//      real evidence that a worker needs its bytes and not its position.
//   3. THE LAST NUMERIC COLUMN specifically. Exports are CRLF throughout
//      (footgun 16), so a trailing `\r` lands on the final field of every
//      row and nowhere else. `parseFloat("112.4\r")` succeeds, which is
//      exactly how this hides in testing.
//   4. TOU comes from the file's TOU column, not from a recomputed
//      HE 6–22 rule (footgun 17).
//   5. The worker's row-widening rule tiles the data region exactly: no
//      gaps, no overlaps, whatever the block boundaries land on.
//
// Everything runs against a SYNTHETIC export generated by test_fixtures.mjs.
// No real data is tracked in or read by this repo. The `--full` mode that once
// timed and verified a 139 MB real export was removed with that file; its last
// recorded result is in docs/status.md.
//
// Run:  node test_ingest.mjs

import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import './test_loader.mjs';
import { exportCsv } from './test_fixtures.mjs';

const { parseHeaderLine, buildColumnPlan, areaHashes, dayOfYear, SLAB_AREAS } = await import(
  './src/ingest/header.ts'
);
const { instantiateParser, parseBytes, afterNextNewline } = await import('./src/ingest/block.ts');
const { createAccumulator, blitBlock, finalizeCase, applyDerived } = await import(
  './src/ingest/pool.ts'
);
const { allAreas } = await import('./src/groupings.ts');
const { HOURS_PER_YEAR, TOU_LABELS } = await import('./src/calendar.ts');

const HOURS = HOURS_PER_YEAR;
const NEWLINE = 10;

let checks = 0;
function ok(label) {
  checks++;
  console.log(`ok - ${label}`);
}

// ---------------------------------------------------------------- the parser

const areas = allAreas();
assert.equal(areas.length, SLAB_AREAS, `the fixture axis must be exactly ${SLAB_AREAS} areas`);

const wasmBytes = readFileSync(new URL('./parser/block.wasm', import.meta.url));
const wasmModule = new WebAssembly.Module(wasmBytes);
const parser = await instantiateParser(wasmModule, areaHashes(areas));
ok('block.wasm instantiates and its area hash table accepts all 43 names');

// ---------------------------------------------------------------- block split

/**
 * The worker's rule, applied to an in-memory buffer instead of a File: a
 * block owns from the first row boundary at/after `start` up to and
 * including the first row terminator at/after `end`.
 */
function wholeRowRanges(bytes, dataStart, blockBytes) {
  const ranges = [];
  for (let start = dataStart; start < bytes.length; start += blockBytes) {
    const from = start === dataStart ? dataStart : afterNextNewline(bytes, start);
    if (from < 0) continue;
    const end = Math.min(start + blockBytes, bytes.length);
    let to = afterNextNewline(bytes, end);
    if (to < 0) to = bytes.length;
    if (to > from) ranges.push([from, to]);
  }
  return ranges;
}

// ---------------------------------------------------------------- reference

/** Independent parser: strings, split, parseFloat. Deliberately naive. */
function referenceCube(text, metrics) {
  const lines = text.split('\n');
  const header = lines[0].replace(/\r$/, '').split(',').map((s) => s.trim());
  const dest = new Map();
  metrics.forEach((name, index) => dest.set(name, index));

  const cube = new Float32Array(SLAB_AREAS * metrics.length * HOURS).fill(NaN);
  const tou = new Uint8Array(HOURS).fill(0xff);
  let rows = 0;

  for (let i = 1; i < lines.length; i++) {
    const line = lines[i].replace(/\r$/, '');
    if (line.length === 0) continue;
    const fields = line.split(',');
    const [month, day] = fields[0].split('/').map(Number);
    const doy = dayOfYear(month, day);
    if (doy < 0) continue; // Feb 29, dropped at ingest (D4)
    const hour = doy * 24 + (Number(fields[1]) - 1);
    const area = areas.indexOf(fields[3].trim());
    if (area < 0) continue;
    tou[hour] = fields[2].trim() === 'OnPeak' ? 1 : 0;
    rows++;
    for (let col = 4; col < fields.length; col++) {
      const metric = dest.get(header[col]);
      if (metric === undefined) continue;
      cube[(area * metrics.length + metric) * HOURS + hour] = parseFloat(fields[col]);
    }
  }
  return { cube, tou, rows };
}

// ---------------------------------------------------------------- comparison

/**
 * Relative spacing of consecutive float32 values, 2^-23. The tolerance is
 * ONE ulp and not a hand-picked epsilon: the cube stores float32, so a
 * difference of one ulp is a difference below the precision the value is
 * kept at. Anything larger is a real parser bug.
 *
 * This is not a free pass. The gate below requires ZERO differences beyond
 * one ulp, and reports the within-one-ulp count as a measured number rather
 * than hiding it — block.c accumulates the integer part and the fraction
 * separately, so it rounds twice where strtod rounds once, and the two
 * 8-digit money columns land on the far side of that on a handful of cells.
 */
const F32_ULP_RELATIVE = 1.1920929e-7;

function compareCubes(expectedCube, actualCube, metrics) {
  const byColumn = new Map();
  let live = 0;
  let differing = 0;
  let beyondOneUlp = 0;
  let maxRelative = 0;

  for (let i = 0; i < expectedCube.length; i++) {
    const expected = expectedCube[i];
    const actual = actualCube[i];
    if (Number.isNaN(expected) && Number.isNaN(actual)) continue;
    live++;
    if (Object.is(expected, actual)) continue;
    differing++;

    const relative =
      Number.isNaN(expected) || Number.isNaN(actual)
        ? Infinity
        : expected === 0
          ? Math.abs(actual)
          : Math.abs((actual - expected) / expected);
    if (relative > maxRelative) maxRelative = relative;
    if (relative > F32_ULP_RELATIVE) beyondOneUlp++;

    // Column name and relative error only, never a value. The habit predates
    // the synthetic fixture and stays: this reporting path is what would run
    // against a real export if anyone ever points it at one.
    const column = metrics[Math.floor(i / HOURS) % metrics.length];
    const seen = byColumn.get(column) ?? { count: 0, worst: 0, beyond: 0 };
    seen.count++;
    if (relative > seen.worst) seen.worst = relative;
    if (relative > F32_ULP_RELATIVE) seen.beyond++;
    byColumn.set(column, seen);
  }
  return { live, differing, beyondOneUlp, maxRelative, byColumn };
}

function assertWithinOneUlp(diff, label) {
  if (diff.differing > 0) {
    console.log(`\n${label}: differences by column (name + relative error only, never a value):`);
    for (const [column, seen] of diff.byColumn) {
      console.log(
        `  ${column}: ${seen.count} cell(s), worst relative ${seen.worst.toExponential(2)}` +
          `${seen.beyond > 0 ? `, ${seen.beyond} BEYOND one float32 ulp` : ' (within one float32 ulp)'}`,
      );
    }
  }
  assert.equal(
    diff.beyondOneUlp,
    0,
    `${label}: ${diff.beyondOneUlp} of ${diff.live} live cells differ by more than one float32 ` +
      `ulp (max relative ${diff.maxRelative.toExponential(2)}). That is a parser bug, not rounding.`,
  );
}

// ---------------------------------------------------------------- run one file

function ingestBuffer(bytes, blockBytes, { reverse = false } = {}) {
  const headerEnd = bytes.indexOf(NEWLINE);
  const header = parseHeaderLine(new TextDecoder().decode(bytes.subarray(0, headerEnd)));
  const plan = buildColumnPlan(header, header.metricNames);
  const accumulator = createAccumulator(plan);

  const ranges = wholeRowRanges(bytes, headerEnd + 1, blockBytes);
  const order = reverse ? [...ranges].reverse() : ranges;
  let rows = 0;
  for (const [from, to] of order) {
    const payload = parseBytes(parser, bytes, from, to, plan.activePlanes);
    rows += payload.rows;
    blitBlock(accumulator, payload);
  }
  return { header, plan, accumulator, ranges, rows };
}

// ---------------------------------------------------------------- the fixture

const sampleBytes = exportCsv();
const sampleText = new TextDecoder().decode(sampleBytes);

assert.ok(sampleText.includes('\r\n'), 'the fixture must be CRLF — footgun 16 is the point');
ok('the synthetic export is CRLF, so the last-column trap is actually exercised');

// A block size that lands boundaries mid-row on purpose.
const BLOCK = 7777;
const run = ingestBuffer(sampleBytes, BLOCK);

// 5. The ranges tile the data region exactly.
{
  const dataStart = sampleBytes.indexOf(NEWLINE) + 1;
  assert.ok(run.ranges.length > 1, 'block size must actually split this file');
  assert.equal(run.ranges[0][0], dataStart);
  assert.equal(run.ranges[run.ranges.length - 1][1], sampleBytes.length);
  for (let i = 1; i < run.ranges.length; i++) {
    assert.equal(
      run.ranges[i][0],
      run.ranges[i - 1][1],
      `block ${i} must start exactly where block ${i - 1} ended`,
    );
  }
  ok(`${run.ranges.length} blocks tile the data region with no gap and no overlap`);
}

const reference = referenceCube(sampleText, run.plan.metrics);
assert.equal(run.rows, reference.rows, 'WASM and reference must see the same row count');
ok(`both parsers see ${run.rows.toLocaleString()} data rows`);

// 1. Cell by cell. Live cells only — NaN on both sides is agreement.
{
  const diff = compareCubes(reference.cube, run.accumulator.cube, run.plan.metrics);
  assertWithinOneUlp(diff, 'the synthetic export');
  ok(
    `${diff.live.toLocaleString()} live cells, ${diff.differing} differing, ` +
      `max relative difference ${diff.maxRelative.toExponential(2)}`,
  );
}

// 3. The last numeric column, specifically. Every value in it carried a
//    trailing \r in the source bytes.
{
  const lastMetric = run.plan.metrics.length - 1;
  const name = run.plan.metrics[lastMetric];
  let compared = 0;
  for (let area = 0; area < SLAB_AREAS; area++) {
    for (let hour = 0; hour < HOURS; hour++) {
      const at = (area * run.plan.metrics.length + lastMetric) * HOURS + hour;
      const expected = Math.fround(reference.cube[at]);
      if (Number.isNaN(expected)) continue;
      assert.ok(
        Object.is(expected, run.accumulator.cube[at]),
        `CRLF trap: last column "${name}" differs at area ${area} hour ${hour}`,
      );
      compared++;
    }
  }
  assert.ok(compared > 0, 'the last-column check must actually compare something');
  ok(`last numeric column "${name}" matches in all ${compared} live cells (CRLF trap)`);
}

// 4. TOU is read, not recomputed.
{
  let covered = 0;
  for (let hour = 0; hour < HOURS; hour++) {
    assert.equal(run.accumulator.tou[hour], reference.tou[hour], `TOU differs at hour ${hour}`);
    if (reference.tou[hour] !== 0xff) covered++;
  }
  assert.ok(covered > 0, 'the sample must cover at least one hour');
  const labels = new Set();
  for (let hour = 0; hour < HOURS; hour++) {
    if (run.accumulator.tou[hour] !== 0xff) labels.add(TOU_LABELS[run.accumulator.tou[hour]]);
  }
  ok(`TOU matches the file's own column across ${covered} covered hour(s): ${[...labels].join(', ')}`);
}

// 2. Block independence.
{
  const reversed = ingestBuffer(sampleBytes, BLOCK, { reverse: true });
  assert.deepEqual(
    new Uint8Array(reversed.accumulator.cube.buffer),
    new Uint8Array(run.accumulator.cube.buffer),
    'cube must be byte-identical when blocks are parsed in reverse order',
  );
  assert.deepEqual(reversed.accumulator.tou, run.accumulator.tou);
  ok('blocks parsed in reverse order produce a byte-identical cube');
}

// A second block size, to prove the result does not depend on where the
// boundaries happen to land.
{
  const other = ingestBuffer(sampleBytes, 1024);
  assert.deepEqual(
    new Uint8Array(other.accumulator.cube.buffer),
    new Uint8Array(run.accumulator.cube.buffer),
    'cube must not depend on block size',
  );
  ok('a different block size produces a byte-identical cube');
}

// Presence, and the leap-year statement D4 requires.
{
  const finalized = finalizeCase(run.accumulator, 'sample.csv', run.header.metricNames, 2036, areas);
  assert.equal(finalized.data.metrics.length, run.plan.metrics.length);
  assert.equal(finalized.data.presence.length, SLAB_AREAS * run.plan.metrics.length);
  let present = 0;
  for (const flag of finalized.data.presence) present += flag;
  assert.equal(
    present,
    SLAB_AREAS * run.plan.metrics.length,
    'every (area, metric) in the sample is present',
  );
  assert.ok(
    finalized.warnings.some((w) => w.includes('Feb 29')),
    'a leap-year case must state that Feb 29 was dropped (D4)',
  );
  ok('presence bitmap is full, and the leap-year Feb 29 drop is stated, not silent');
}

// ---------------------------------------------------------------- calculated columns
//
// `Gen - Load` has no source column: its plane is filled after the blit from
// two other planes. Two things can go wrong silently — the plane stays NaN and
// every pane reads it as absent, or it is filled from the wrong metric index
// and looks like plausible MWh. Both are checked against the reference cube.
{
  const DERIVED = 'Gen - Load';
  const metrics = [...run.header.metricNames, DERIVED];
  const plan = buildColumnPlan(run.header, metrics);
  const accumulator = createAccumulator(plan);
  for (const [from, to] of run.ranges) {
    blitBlock(accumulator, parseBytes(parser, sampleBytes, from, to, plan.activePlanes));
  }

  const derivedIndex = plan.metrics.indexOf(DERIVED);
  const genIndex = plan.metrics.indexOf('Generation (MWh)');
  const loadIndex = plan.metrics.indexOf('Load (MWh)');
  assert.ok(derivedIndex >= 0 && genIndex >= 0 && loadIndex >= 0, 'operands must be on the axis');

  // Before the fill pass the plane is untouched NaN, so a missing call cannot
  // masquerade as zeros.
  const at = (metric, area, hour) =>
    accumulator.cube[(area * plan.metrics.length + metric) * HOURS + hour];
  assert.ok(Number.isNaN(at(derivedIndex, 0, 0)), 'the derived plane must start absent');
  assert.equal(plan.presence[derivedIndex], 0, 'no source column feeds it, so presence starts 0');

  applyDerived(accumulator);
  assert.equal(plan.presence[derivedIndex], 1, 'presence must be set once the plane is built');

  let compared = 0;
  for (let area = 0; area < SLAB_AREAS; area++) {
    for (let hour = 0; hour < HOURS; hour++) {
      const gen = at(genIndex, area, hour);
      const load = at(loadIndex, area, hour);
      const got = at(derivedIndex, area, hour);
      if (Number.isNaN(gen) || Number.isNaN(load)) {
        assert.ok(Number.isNaN(got), `absent operand must stay absent at area ${area} hour ${hour}`);
        continue;
      }
      assert.ok(
        Object.is(got, Math.fround(gen - load)),
        `Gen - Load wrong at area ${area} hour ${hour}`,
      );
      compared++;
    }
  }
  assert.ok(compared > 0, 'the derived check must actually compare something');
  ok(`Gen - Load computed for all ${compared} live cells, absent where an operand is`);

  // Dropping an operand must leave it absent rather than half-built.
  const without = buildColumnPlan(run.header, [...run.header.metricNames, DERIVED].filter(
    (name) => name !== 'Load (MWh)',
  ));
  const partial = createAccumulator(without);
  for (const [from, to] of run.ranges) {
    blitBlock(partial, parseBytes(parser, sampleBytes, from, to, without.activePlanes));
  }
  applyDerived(partial);
  assert.equal(
    without.presence[without.metrics.indexOf(DERIVED)],
    0,
    'without an operand the calculated column must stay absent, not be built from nothing',
  );
  ok('Gen - Load stays absent when an operand was not retained');

  // The second calculated column, and the one whose meaning depends on a sign
  // convention the schema does not state. Net Interchange = Import - Export is
  // net imports only while both operands are unsigned magnitudes, so the fill
  // pass reports it when one is not.
  const NET = 'Net Interchange (MWh)';
  const netPlan = buildColumnPlan(run.header, [...run.header.metricNames, NET]);
  const netAcc = createAccumulator(netPlan);
  for (const [from, to] of run.ranges) {
    blitBlock(netAcc, parseBytes(parser, sampleBytes, from, to, netPlan.activePlanes));
  }
  const netWarnings = applyDerived(netAcc);
  const netIndex = netPlan.metrics.indexOf(NET);
  const importIndex = netPlan.metrics.indexOf('Import Flow(MWh)');
  const exportIndex = netPlan.metrics.indexOf('Export Flow (MWh)');
  const netAt = (metric, area, hour) =>
    netAcc.cube[(area * netPlan.metrics.length + metric) * HOURS + hour];

  let netCompared = 0;
  for (let area = 0; area < SLAB_AREAS; area++) {
    for (let hour = 0; hour < HOURS; hour++) {
      const imported = netAt(importIndex, area, hour);
      const exported = netAt(exportIndex, area, hour);
      if (Number.isNaN(imported) || Number.isNaN(exported)) continue;
      assert.ok(
        Object.is(netAt(netIndex, area, hour), Math.fround(imported - exported)),
        `Net Interchange wrong at area ${area} hour ${hour}`,
      );
      netCompared++;
    }
  }
  assert.ok(netCompared > 0, 'the net interchange check must actually compare something');
  ok(`Net Interchange = Import - Export for all ${netCompared} live cells`);

  // The fixture happens to emit Export Flow as negatives, which is exactly the
  // convention the guard exists to catch: the arithmetic is unchanged but the
  // result stops being a net figure, and that has to be said rather than
  // plotted.
  assert.equal(netWarnings.length, 1, `expected one sign warning, got ${netWarnings.length}`);
  assert.ok(
    netWarnings[0].includes('Export Flow (MWh)') && netWarnings[0].includes('sign convention'),
    `the warning must name the signed operand: ${netWarnings[0]}`,
  );
  ok('a negative operand is reported instead of silently inverting the net figure');

  // Both operands unsigned: the assumption the column is named for, and the
  // case that must stay quiet or the warning is noise nobody reads.
  for (let area = 0; area < SLAB_AREAS; area++) {
    const base = (area * netPlan.metrics.length + exportIndex) * HOURS;
    for (let hour = 0; hour < HOURS; hour++) netAcc.cube[base + hour] = Math.abs(netAcc.cube[base + hour]);
  }
  assert.deepEqual(applyDerived(netAcc), [], 'unsigned operands must not raise a sign warning');
  ok('unsigned operands raise nothing');
}

// The third calculated column divides rather than subtracts. Division brings
// one failure the subtraction path cannot have: x/0 is Infinity, which is a
// finite-looking number to every kernel downstream and no NaN guard catches
// it (footgun 21). It has to land as absent instead.
{
  const RATIO = 'Generation / Installed Capacity';
  const plan = buildColumnPlan(run.header, [...run.header.metricNames, RATIO]);
  const accumulator = createAccumulator(plan);
  for (const [from, to] of run.ranges) {
    blitBlock(accumulator, parseBytes(parser, sampleBytes, from, to, plan.activePlanes));
  }

  const ratioIndex = plan.metrics.indexOf(RATIO);
  const genIndex = plan.metrics.indexOf('Generation (MWh)');
  const capIndex = plan.metrics.indexOf('Installed Capacity (MW)');
  assert.ok(ratioIndex >= 0 && genIndex >= 0 && capIndex >= 0, 'operands must be on the axis');
  const at = (metric, area, hour) =>
    accumulator.cube[(area * plan.metrics.length + metric) * HOURS + hour];

  // One forced zero denominator, so the guard is exercised whatever the
  // fixture happens to emit. It has to land on a cell both operands cover --
  // the sample export is sparse, and a zero in an hour nothing reported is
  // not a zero denominator, it is still just absent.
  let zeroed = false;
  for (let area = 0; area < SLAB_AREAS && !zeroed; area++) {
    for (let hour = 0; hour < HOURS; hour++) {
      if (Number.isNaN(at(genIndex, area, hour)) || Number.isNaN(at(capIndex, area, hour))) continue;
      accumulator.cube[(area * plan.metrics.length + capIndex) * HOURS + hour] = 0;
      zeroed = true;
      break;
    }
  }
  assert.ok(zeroed, 'the fixture must cover at least one (Generation, Installed Capacity) cell');

  const warnings = applyDerived(accumulator);
  let compared = 0;
  for (let area = 0; area < SLAB_AREAS; area++) {
    for (let hour = 0; hour < HOURS; hour++) {
      const gen = at(genIndex, area, hour);
      const capacity = at(capIndex, area, hour);
      const got = at(ratioIndex, area, hour);
      if (Number.isNaN(gen) || Number.isNaN(capacity) || capacity === 0) {
        assert.ok(Number.isNaN(got), `a zero or absent denominator must stay absent, not Infinity`);
        continue;
      }
      assert.ok(
        Object.is(got, Math.fround(gen / capacity)),
        `${RATIO} wrong at area ${area} hour ${hour}`,
      );
      compared++;
    }
  }
  assert.ok(compared > 0, 'the ratio check must actually compare something');
  assert.ok(
    warnings.some((w) => w.includes(RATIO) && w.includes('Installed Capacity (MW)')),
    `a zero denominator must be reported: ${JSON.stringify(warnings)}`,
  );
  ok(`${RATIO} computed for ${compared} live cells; zero denominators absent and reported`);
}

console.log(`\n${checks} checks passed`);
